"""
unet/inference/visualize.py

Visualizes the Reliability-Region Map generated by the U-Net.
"""

import matplotlib.pyplot as plt
import torch
import numpy as np
from pathlib import Path

def plot_reliability_map(input_img, gt_mask, pred_mask, save_path=None):
    """
    Plots a 3-panel comparison: Input (Magnitude), GT Mask, and U-Net Prediction.
    input_img: (2, H, W) tensor or numpy array
    gt_mask: (1, H, W)
    pred_mask: (1, H, W) - continuous values [0, 1]
    """
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    # Panel 1: Input Magnitude (Channel 0)
    axes[0].imshow(input_img[0], cmap='jet')
    axes[0].set_title("Input: DAS Magnitude")
    axes[0].axis('off')
    
    # Panel 2: Ground Truth Mask
    axes[1].imshow(gt_mask[0], cmap='gray')
    axes[1].set_title("Ground Truth Mask")
    axes[1].axis('off')
    
    # Panel 3: U-Net Reliability Map
    im = axes[2].imshow(pred_mask[0], cmap='hot', vmin=0, vmax=1)
    axes[2].set_title("U-Net Reliability Map")
    axes[2].axis('off')
    plt.colorbar(im, ax=axes[2], fraction=0.046, pad=0.04)
    
    plt.tight_layout()
    
    if save_path:
        Path(save_path).parent.mkdir(exist_ok=True)
        plt.savefig(save_path, dpi=300)
        print(f"Visualization saved to {save_path}")
    else:
        plt.show()